/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OjjhYnyepoB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function Portifolio() {
  const [isPortuguese, setIsPortuguese] = useState(true);
  const toggleLanguage = () => {
    setIsPortuguese((prevState) => !prevState);
  };
  return (
    <div className="flex flex-col min-h-100dvh">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            {isPortuguese ? "In\u00EDcio" : "Home"}
          </Link>
          <Link
            href="#projects"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            {isPortuguese ? "Projetos" : "Projects"}
          </Link>
          <Link
            href="#skills"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            {isPortuguese ? "Habilidades" : "Skills"}
          </Link>
          <Link
            href="#contact"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            {isPortuguese ? "Contato" : "Contact"}
          </Link>
        </nav>
        <Button variant="outline" onClick={toggleLanguage} className="ml-4">
          {isPortuguese ? "English" : "Portugu\u00EAs"}
        </Button>
      </header>
      <main className="flex-1">
        <section id="introduction" className="w-full py-12 md:py-24 lg:py-32">
          <div className="px-4 md:px-6">
            <div className="grid md:gap-96 gap-6 lg:grid-cols-[1fr_400px] xl:grid-cols-[1fr_600px] max-w-fit mx-auto space-y-8 lg:space-y-0">
              <div className="flex flex-col justify-center items-center space-y-4 ">
                <div className="space-y-2 max-w-600px text-center">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    {isPortuguese ? "Felipe de Sousa" : "Felipe de Sousa"}
                  </h1>
                  <h2 className="text-xl font-semibold text-muted-foreground">
                    {isPortuguese
                      ? "Backend Software Engineer | Java | Microsservi\u00E7os"
                      : "Backend Software Engineer | Java | Microservices"}
                  </h2>
                  <p className="max-w-600px text-muted-foreground md:text-l">
                    {isPortuguese
                      ? "Desenvolvedor backend com foco em Java e arquitetura de microsservi\u00E7os, atuando atualmente em produtos globais da Michelin Connected Fleet (Sascar) em parceria com a Meta, com impacto em opera\u00E7\u00F5es nas Am\u00E9ricas e Europa. Trabalho com APIs REST, integra\u00E7\u00E3o entre servi\u00E7os, mensageria com Kafka e autentica\u00E7\u00E3o e autoriza\u00E7\u00E3o com Keycloak, aplicando OAuth2, OpenID Connect e JWT. No dia a dia, uso Spring Boot, PostgreSQL e OpenShift para evoluir solu\u00E7\u00F5es com foco em escalabilidade, resili\u00EAncia, seguran\u00E7a e confiabilidade operacional."
                      : "Backend engineer focused on Java and microservices architecture, currently working on global Michelin Connected Fleet (Sascar) products in partnership with Meta, supporting operations across the Americas and Europe. I build REST APIs, service-to-service integrations, Kafka-based event flows, and authentication and authorization with Keycloak using OAuth2, OpenID Connect, and JWT. My day-to-day stack includes Spring Boot, PostgreSQL, and OpenShift to evolve solutions with a strong focus on scalability, resiliency, security, and operational reliability."}
                  </p>
                </div>
              </div>
              <img
                src="/profile.png"
                width="550"
                height="550"
                alt={"profile"}
                draggable="false"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="projects"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  {isPortuguese ? "Projetos Destacados" : "Featured Projects"}
                </h2>
                <p className="max-w-900px text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  {isPortuguese
                    ? "Projetos que demonstram experi\u00EAncia em backend, integra\u00E7\u00E3o entre servi\u00E7os, seguran\u00E7a e sistemas distribu\u00EDdos."
                    : "Projects that highlight backend engineering, service integration, security, and distributed systems experience."}
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-7xl items-start gap-6 py-12 grid-cols-[repeat(auto-fit,minmax(360px,1fr))]">
              <Card>
                <CardHeader>
                  <img
                    src="/pesquisa-integrada.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Sistema de Pesquisa Integrada do TCU"
                        : "Integrated Search System"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Sistema de Pesquisa Integrada (TCU)"
                        : "Integrated Search System (TCU)"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Desenvolvimento do sistema de pesquisa textual utilizando Java, Spring Framework e Kotlin. Atua\u00E7\u00E3o em testes unit\u00E1rios, integra\u00E7\u00E3o com frontend Angular, otimiza\u00E7\u00E3o de pipelines CI/CD e uso de Elasticsearch, Solr, Oracle e PostgreSQL em ambiente corporativo de alta criticidade."
                        : "Development of a text search platform using Java, Spring Framework, and Kotlin. Worked on unit tests, Angular frontend integration, CI/CD pipeline optimization, and search architecture with Elasticsearch, Solr, Oracle, and PostgreSQL in a high-criticality enterprise environment."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Spring Framework</Badge>
                    <Badge>Kotlin</Badge>
                    <Badge>Angular</Badge>
                    <Badge>JUnit</Badge>
                    <Badge>Elasticsearch</Badge>
                    <Badge>Solr</Badge>
                    <Badge>Oracle</Badge>
                    <Badge>PostgreSQL</Badge>
                    <Badge>CI/CD</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://pesquisa.apps.tcu.gov.br/pesquisa/integrada"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Preview
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/skuba.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Skuba - Sistema de Monitoramento Kubernetes - Spring Batch"
                        : "Skuba - Kubernetes - Spring Batch Monitoring System"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Skuba - Sistema de Monitoramento Kubernetes - Spring Batch"
                        : "Skuba: Kubernetes - Spring Batch Monitoring System"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Sistema web para monitoramento e execução de processos batch em ambiente Kubernetes. Backend em Kotlin/Spring Boot centraliza dados a partir das tabelas de metadados do Spring Batch e expõe endpoints para acompanhamento e execução manual; frontend em React + TypeScript + Vite oferece dashboard, histórico e visão operacional."
                        : "Web system for monitoring and executing batch processes in Kubernetes. A Kotlin/Spring Boot backend centralizes data from Spring Batch metadata tables and exposes endpoints for tracking and manual execution; a React + TypeScript + Vite frontend provides dashboards, history, and operational views."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Kotlin</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>Spring Batch</Badge>
                    <Badge>Spring Cloud</Badge>
                    <Badge>Kubernetes</Badge>
                    <Badge>Kafka</Badge>
                    <Badge>Docker</Badge>
                    <Badge>React</Badge>
                    <Badge>TypeScript</Badge>
                    <Badge>Vite</Badge>
                    <Badge>MUI</Badge>
                    <Badge>CI/CD</Badge>
                  </div>
                  <div className="flex gap-2">
                    <div className="inline-flex h-8 items-center justify-center rounded-md border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50">
                      {isPortuguese
                        ? "Projeto Corporativo"
                        : "Corporative Project"}
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/mcf.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Gest\u00E3o de Frotas - Plataforma global Michelin Connected Fleet"
                        : "Fleet Management - Michelin Connected Fleet global platform"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Michelin Connected Fleet - Gest\u00E3o de Frotas"
                        : "Michelin Connected Fleet - Fleet Management"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Atua\u00E7\u00E3o em plataforma global de gest\u00E3o de frotas em larga escala, com impacto em opera\u00E7\u00F5es nas Am\u00E9ricas e Europa. Contribui\u00E7\u00E3o em desenvolvimento backend, integra\u00E7\u00E3o entre servi\u00E7os, processamento orientado a eventos com Kafka e evolu\u00E7\u00E3o de solu\u00E7\u00F5es com foco em performance, escalabilidade e confiabilidade operacional."
                        : "Worked on a global large-scale fleet management platform with impact across operations in the Americas and Europe. Contributed to backend development, service integration, Kafka-based event processing, and solution evolution focused on performance, scalability, and operational reliability."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>Kafka</Badge>
                    <Badge>PostgreSQL</Badge>
                    <Badge>OpenShift</Badge>
                    <Badge>Kubernetes</Badge>
                    <Badge>Event-Driven Architecture</Badge>
                    <Badge>Service Integration</Badge>
                    <Badge>Reliability</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://connectedfleet.michelin.com/"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Preview
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/mcf.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Sasweb - Plataforma corporativa Michelin Connected Fleet"
                        : "Sasweb - Michelin Connected Fleet corporate platform"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Sasweb - Plataforma corporativa Michelin Connected Fleet"
                        : "Sasweb - Michelin Connected Fleet corporate platform"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Projeto backend corporativo global com foco na evolu\u00E7\u00E3o de microsservi\u00E7os em Java e Spring Boot para a Michelin Connected Fleet (Sascar), suportando opera\u00E7\u00F5es nas Am\u00E9ricas e Europa. Atua\u00E7\u00E3o em APIs REST, integra\u00E7\u00E3o entre servi\u00E7os, autentica\u00E7\u00E3o e autoriza\u00E7\u00E3o com Keycloak e melhorias arquiteturais voltadas a resili\u00EAncia, seguran\u00E7a e escalabilidade."
                        : "Global enterprise backend project focused on evolving Java and Spring Boot microservices for Michelin Connected Fleet (Sascar), supporting operations across the Americas and Europe. Worked on REST APIs, service integrations, authentication and authorization with Keycloak, and architecture improvements aimed at resiliency, security, and scalability."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Java 21</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>REST APIs</Badge>
                    <Badge>Microservices</Badge>
                    <Badge>Keycloak</Badge>
                    <Badge>OAuth2</Badge>
                    <Badge>OpenID Connect</Badge>
                    <Badge>JWT</Badge>
                    <Badge>PostgreSQL</Badge>
                  </div>
                  <div className="flex gap-2">
                    <div className="inline-flex h-8 items-center justify-center rounded-md border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50">
                      {isPortuguese
                        ? "Projeto Corporativo"
                        : "Corporate Project"}
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/gw6.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Galaxy Watch6 ESP32 Remake - Sistema embarcado com ESP32, sensores e MQTT"
                        : "Galaxy Watch6 ESP32 Remake - Embedded system with ESP32, sensors, and MQTT"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Galaxy Watch6 ESP32 Remake"
                        : "Galaxy Watch6 ESP32 Remake"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Protótipo de sistema embarcado (UnB) que recria funcionalidades de um smartwatch moderno usando ESP32. Integra leituras em tempo real do sensor DHT11 (temperatura/umidade) e um sensor capacitivo KY-031 para interação do usuário, alternando modos e exibindo dados dinamicamente em um display OLED. Publica telemetria via MQTT para brokers (incluindo opções públicas) e integração com dashboards como o ThingsBoard, permitindo monitoramento remoto e visualizações configuráveis."
                        : "Embedded systems prototype (UnB) that recreates modern smartwatch-like sensor features using an ESP32. It reads real-time data from a DHT11 sensor (temperature/humidity) and uses a KY-031 capacitive sensor for user interaction, switching modes and rendering sensor data dynamically on an OLED display. Telemetry is published over MQTT to brokers (including public options) and can be integrated with dashboards such as ThingsBoard for remote monitoring and configurable visualizations."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>ESP32</Badge>
                    <Badge>C</Badge>
                    <Badge>IoT</Badge>
                    <Badge>MQTT</Badge>
                    <Badge>ESP-IDF</Badge>
                    <Badge>CMake</Badge>
                    <Badge>ThingsBoard</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/fsousac/GalaxyWatch6-ESP32-Remake"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="chicoliro.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Robô Seguidor de Linha com Monitoramento em Tempo Real (UnB)"
                        : "Line Follower Robot with Real-Time Monitoring (UnB)"
                    }
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    draggable="false"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Robô Seguidor de Linha com Monitoramento em Tempo Real (UnB)"
                        : "Line Follower Robot with Real-Time Monitoring (Unb)"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Desenvolvimento de sistema integrado para controle e monitoramento de robô autônomo. API em Nest.js processando 50+ requisições/segundo e armazenamento em MongoDB. Comunicação bidirecional via WebSocket com frontend em Angular para atualizações em <100ms. 85% de cobertura de testes (Jest, Karma) e redução de 40% no consumo de energia."
                        : "Development of an integrated system for autonomous robot control and monitoring. Nest.js API handling 50+ requests per second with data stored in MongoDB. Bidirectional communication via WebSocket with an Angular frontend for updates in under 100ms. Achieved 85% test coverage (Jest, Karma) and reduced energy consumption by 40%."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Angular</Badge>
                    <Badge>TypeScript</Badge>
                    <Badge>Nest.js</Badge>
                    <Badge>C++</Badge>
                    <Badge>Arduino</Badge>
                    <Badge>MongoDB</Badge>
                    <Badge>WebSocket</Badge>
                    <Badge>Jest</Badge>
                    <Badge>Selenium</Badge>
                    <Badge>Karma</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/orgs/pi1-2024-ChicoLiro/repositories"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/weshortten.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "WeShortten - Encurtador de URLs (Java/Spring Boot)"
                        : "WeShortten - URL Shortener (Java/Spring Boot)"
                    }
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    draggable="false"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "WeShortten - Encurtador de URLs (Java/Spring Boot)"
                        : "WeShortten - URL Shortener (Java/Spring Boot)"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Encurtador de URLs com API RESTful, geração de códigos curtos, redirecionamento rápido e rastreamento de acessos (IP, user agent, timestamp). Deploy automatizado com Docker e Traefik."
                        : "URL shortener with RESTful API, short code generation, fast redirection, and access tracking (IP, user agent, timestamp). Automated deploy with Docker and Traefik."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>PostgreSQL</Badge>
                    <Badge>Docker</Badge>
                    <Badge>Traefik</Badge>
                    <Badge>JPA/Hibernate</Badge>
                    <Badge>Lombok</Badge>
                    <Badge>Gradle</Badge>
                    <Badge>REST API</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/fsousac/weshortten"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/santander-devweek.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "API RESTful Santander DevWeek 2023"
                        : "RESTful API Santander DevWeek 2023"
                    }
                    draggable="false"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "API RESTful Santander DevWeek 2023"
                        : "RESTful API Santander DevWeek 2023"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "Desenvolvimento de uma API bancária simulando transações financeiras. Implementação de autenticação JWT com Spring Security. Utilização de Spring Data JPA para operações CRUD e transações ACID. Configuração de ambiente containerizado com Docker para PostgreSQL e aplicação Spring Boot."
                        : "Development of a banking API simulating financial transactions. Implementation of JWT authentication with Spring Security. Use of Spring Data JPA for CRUD operations and ACID transactions. Containerized environment setup with Docker for PostgreSQL and the Spring Boot application."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>JWT</Badge>
                    <Badge>Spring Security</Badge>
                    <Badge>Spring Data JPA</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>Docker</Badge>
                    <Badge>REST</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/fsousac/santader-dev-week-2023"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <img
                    src="/picpay.png"
                    width="550"
                    height="310"
                    alt={
                      isPortuguese
                        ? "Code Challenge Picpay Simplificado"
                        : "Code Challenge Simplified Picpay"
                    }
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                    draggable="false"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div>
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Code Challenge Picpay Simplificado"
                        : "Code Challenge Simplified Picpay"}
                    </h3>
                    <p className="text-muted-foreground">
                      {isPortuguese
                        ? "API para transferências entre usuários com autenticação básica. Resolução de concorrência em transações com @Transactional e locks otimistas. Testes de carga com JMeter para suportar 500+ transações simultâneas. Sistema escalável utilizado como case de estudo em entrevistas técnicas."
                        : "API for user-to-user transfers with basic authentication. Concurrency resolution in transactions using @Transactional and optimistic locking. Load testing with JMeter to support 500+ simultaneous transactions. Scalable system used as a case study in technical interviews."}
                    </p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Spring Boot</Badge>
                    <Badge>Spring Security</Badge>
                    <Badge>Hibernate</Badge>
                    <Badge>MySQL</Badge>
                    <Badge>JMeter</Badge>
                    <Badge>REST</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/fsousac/picpay-code-challenge"
                      target="_blank"
                      className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section id="skills" className="w-full py-12 md:py-24 lg:py-32">
          <div className="px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  {isPortuguese ? "Minhas Habilidades" : "My Skills"}
                </h2>
                <p className="max-w-900px text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  {isPortuguese
                    ? "Tenho um conjunto diversificado de habilidades que me permitem construir aplica\u00E7\u00F5es web de alta qualidade, escal\u00E1veis e amig\u00E1veis ao usu\u00E1rio."
                    : "I have a diverse set of skills that allow me to build high-quality, scalable, and user-friendly web applications."}
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-7xl items-start gap-6 py-12 md:grid-cols-2 xl:grid-cols-4 xl:gap-8">
              <Card>
                <CardContent className="space-y-2">
                  <div className="flex items-center gap-2 pt-4">
                    <CodeIcon className="w-6 h-6 text-primary" />
                    <h3 className="text-xl font-bold ">
                      {isPortuguese ? "Frontend" : "Frontend"}
                    </h3>
                  </div>
                  <p className="text-muted-foreground">
                    {isPortuguese
                      ? "Experi\u00EAncia em interfaces web modernas, integra\u00E7\u00E3o com APIs e constru\u00E7\u00E3o de experi\u00EAncias consistentes para produtos corporativos."
                      : "Experience building modern web interfaces, API integrations, and consistent user experiences for enterprise products."}
                  </p>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>JavaScript</Badge>
                    <Badge>TypeScript</Badge>
                    <Badge>React</Badge>
                    <Badge>Next.js</Badge>
                    <Badge>Angular</Badge>
                    <Badge>Vue</Badge>
                    <Badge>HTML5</Badge>
                    <Badge>CSS3</Badge>
                    <Badge>Sass</Badge>
                    <Badge>Tailwind CSS</Badge>
                    <Badge>Vite</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-2">
                  <div className="flex items-center gap-2 pt-4">
                    <LaptopIcon className="w-6 h-6 text-primary" />
                    <h3 className="text-xl font-bold">
                      {isPortuguese ? "Backend" : "Backend"}
                    </h3>
                  </div>
                  <p className="text-muted-foreground">
                    {isPortuguese
                      ? "Desenvolvimento de servi\u00E7os backend e APIs com foco em microsservi\u00E7os, integra\u00E7\u00E3o entre servi\u00E7os e confiabilidade em produ\u00E7\u00E3o."
                      : "Backend service and API development focused on microservices, service integration, and production reliability."}
                  </p>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Java</Badge>
                    <Badge>Kotlin</Badge>
                    <Badge>Python</Badge>
                    <Badge>Node.js</Badge>
                    <Badge>C++</Badge>
                    <Badge>C</Badge>
                    <Badge>Spring Framework</Badge>
                    <Badge>NestJS</Badge>
                    <Badge>Django</Badge>
                    <Badge>Spring Security</Badge>
                    <Badge>REST APIs</Badge>
                    <Badge>Microservices</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-2">
                  <div className="flex items-center gap-2 pt-4">
                    <DatabaseIcon className="w-6 h-6 text-primary" />
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Arquitetura e Dados"
                        : "Architecture & Data"}
                    </h3>
                  </div>
                  <p className="text-muted-foreground">
                    {isPortuguese
                      ? "Experi\u00EAncia com arquitetura orientada a eventos, autentica\u00E7\u00E3o corporativa, persist\u00EAncia relacional e mecanismos de busca."
                      : "Experience with event-driven architecture, enterprise authentication, relational persistence, and search technologies."}
                  </p>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Kafka</Badge>
                    <Badge>Keycloak</Badge>
                    <Badge>JWT</Badge>
                    <Badge>OAuth2</Badge>
                    <Badge>OpenID Connect</Badge>
                    <Badge>PostgreSQL</Badge>
                    <Badge>Oracle</Badge>
                    <Badge>Elasticsearch</Badge>
                    <Badge>Solr</Badge>
                    <Badge>MongoDB</Badge>
                    <Badge>Prisma</Badge>
                    <Badge>SQL</Badge>
                    <Badge>PL/SQL</Badge>
                    <Badge>MQTT</Badge>
                    <Badge>Event-Driven Architecture</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-2">
                  <div className="flex items-center gap-2 pt-4">
                    <PenToolIcon className="w-6 h-6 text-primary" />
                    <h3 className="text-xl font-bold">
                      {isPortuguese
                        ? "Infraestrutura e Engenharia"
                        : "Infrastructure & Engineering"}
                    </h3>
                  </div>
                  <p className="text-muted-foreground">
                    {isPortuguese
                      ? "Ferramentas e pr\u00E1ticas de entrega, qualidade, observabilidade e opera\u00E7\u00E3o para ambientes distribu\u00EDdos."
                      : "Delivery, quality, observability, and operations practices for distributed environments."}
                  </p>
                  <div className="flex gap-2 flex-wrap">
                    <Badge>Git</Badge>
                    <Badge>GitHub</Badge>
                    <Badge>AWS</Badge>
                    <Badge>Azure Cloud</Badge>
                    <Badge>Google Cloud</Badge>
                    <Badge>Docker</Badge>
                    <Badge>Kubernetes</Badge>
                    <Badge>OpenShift</Badge>
                    <Badge>Spring Cloud</Badge>
                    <Badge>Figma</Badge>
                    <Badge>Scrum</Badge>
                    <Badge>Kanban</Badge>
                    <Badge>XP</Badge>
                    <Badge>TDD</Badge>
                    <Badge>JUnit</Badge>
                    <Badge>Jest</Badge>
                    <Badge>Cypress</Badge>
                    <Badge>Selenium</Badge>
                    <Badge>SonarQube</Badge>
                    <Badge>Sentry</Badge>
                    <Badge>Test Automation</Badge>
                    <Badge>Observability</Badge>
                    <Badge>CI/CD</Badge>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section
          id="contact"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  {isPortuguese ? "Entre em Contato" : "Get in Touch"}
                </h2>
                <p className="max-w-900px text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  {isPortuguese
                    ? "Tem um projeto em mente ou apenas quer dizer um oi? Preencha o formul\u00E1rio abaixo e entrarei em contato com voc\u00EA o assim que poss\u00EDvel."
                    : "Have a project in mind or just want to say hello? Fill out the form below and I'll get back to you as\n                  soon as possible."}
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form
                  action="https://formspree.io/f/xqabperw"
                  method="POST"
                  className="flex flex-col gap-4"
                >
                  <Input
                    type="text"
                    name="name"
                    placeholder={isPortuguese ? "Nome" : "Name"}
                    className="max-w-lg flex-1"
                  />
                  <Input
                    type="email"
                    name="email"
                    placeholder="Email"
                    className="max-w-lg flex-1"
                  />
                  <Textarea
                    placeholder={isPortuguese ? "Mensagem" : "Message"}
                    name="message"
                    className="max-w-lg flex-1"
                  />
                  <Button type="submit">
                    {isPortuguese ? "Enviar" : "Submit"}
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function CodeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function DatabaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  );
}

function LaptopIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  );
}

function PenToolIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z" />
      <path d="m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18" />
      <path d="m2.3 2.3 7.286 7.286" />
      <circle cx="11" cy="11" r="2" />
    </svg>
  );
}
